---
title: 'Intro to Bioinformatics Example: Check output from tools'
author: "Chaochih Liu"
date: "September 19, 2017"
output: html_document
---

## Intro to Bioinformatics

---

#### How to check if the output produced by your tools is correct?

First, we will create test data to use for our example.

```{r}
df <- data.frame(
    v1 = c(1:6),
    v2 = c(6:1),
    v3 = c(21:26)
)
#   View what is stored is "df"
df
```

Now, we will add columns 1, 2, and 3 together and save our output to a new variable.

```{r}
addition <- df$v1 + df$v2 + df$v3
#   View what is stored in "addition"
addition
```

Next, we will randomly select 2 rows to verify our output makes sense.

```{r}
#   Test 1 - row 1
df[1, 1] # row 1, column 1 value is 1
df[1, 2] # row 1, column 2 value is 6
df[1, 3] # row 1, column 3 value is 21

#   Manually add together values in columns from row 1
1 + 6 + 21
```

Now, let's try values from row 4.

```{r}
#   Test 2 - row 4
df[4, 1] # row 4, column 1 value is 4
df[4, 2] # row 4, column 2 value is 3
df[4, 3] # row 4, column 3 value is 24

#   Manually add together values in columns from row 4
4 + 6 + 21
```

