#!/bin/bash
#PBS -l mem=64gb,nodes=1:ppn=16,walltime=4:00:00
#PBS -m abe
#PBS -M youremail@umn.edu
#PBS -q lab

module load java

export _JAVA_OPTIONS="-Xmx63g"
java -jar /panfs/roc/groups/9/morrellp/shared/Software/GATK-3.6/GenomeAnalysisTK.jar\
  -T GenotypeGVCFs\
  -R /panfs/roc/groups/9/morrellp/shared/References/Reference_Sequences/Barley/Morex/barley_RefSeq_v1.0/barley_pseudomolecules_parts.fa\
  -V /panfs/roc/groups/9/morrellp/llei/GATK_does_naught_compute/GATK_out/ND26104_RawGLs.g.vcf\ #replace the path and your g.vcf file name
  -V /panfs/roc/groups/9/morrellp/llei/GATK_does_naught_compute/GATK_out/ND26036_RawGLs.g.vcf\ #replace the path and your g.vcf file name
  -o /panfs/roc/groups/9/morrellp/llei/GATK_does_naught_compute/GATK_out/ND26104_ND26036.vcf\ #replace the path and give the name for the output vcf file
  --heterozygosity 0.008\
  --sample_ploidy 1\
