#!/bin/bash
#PBS -l mem=64gb,nodes=1:ppn=16,walltime=4:00:00
#PBS -m abe
#PBS -M llei@umn.edu
#PBS -q lab

module load java

export _JAVA_OPTIONS="-Xmx63g"
java -jar /panfs/roc/groups/9/morrellp/shared/Software/GATK-3.6/GenomeAnalysisTK.jar\
  -T HaplotypeCaller\
  -R /panfs/roc/groups/9/morrellp/shared/References/Reference_Sequences/Barley/Morex/barley_RefSeq_v1.0/barley_pseudomolecules_parts.fa\
  -I /panfs/roc/scratch/llei/GATK_samples/ND26036.bam\
  -o /panfs/roc/groups/9/morrellp/llei/GATK_does_naught_compute/GATK_out/ND26036_RawGLs.g.vcf\
  -nct 16\
  --genotyping_mode DISCOVERY\
  --heterozygosity 0.008\
  --emitRefConfidence GVCF\
  -variant_index_type LINEAR\
  -variant_index_parameter 128000
